### ISSUE TITLE
402 On payment

### ISSUE THREAD

**Issue by dsfrederic** [GalloDaSballo/Strapi-Gatsby-Ecommerce-Backend#1]
Hi @GalloDaSballo 👋 

This repository is not working for me:

while going through the payment process the frontend shows me the success page BUT in stripe, it is marked as incomplete.
in Strapi I'm seeing a 402 HTTP code for the POST /orders request. 

Can you help me to solve this issue?

FYI: I've bought your Udemy course and asked the question over there as well.

**Comment by GalloDaSballo** [comment]
Replied in the Q&A
